'use strict';
const $ = selector => document.querySelector(selector);
const chat = $('#chat'), input = $('#input'), send = $('#send'), trace = $('#trace');
const initialChat = chat.innerHTML, initialTrace = trace.innerHTML;
let busy = false, archived = false, evaluation;
const names = {search_travel_guide:'攻略检索',get_weather_info:'天气查询',query_route:'路线导航',recommend_hotels:'酒店推荐',get_hotel_reviews:'酒店评价'};
function esc(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function format(value){return esc(value).replace(/^#{1,4}\s+(.+)$/gm,'<span class="message-title">$1</span>').replace(/\*\*(.+?)\*\*/g,'<span class="message-strong">$1</span>');}
function setBusy(value){busy=value;document.querySelectorAll('[data-q],#send,#reset,#replay').forEach(b=>b.disabled=value);input.disabled=value;}
function setMode(isArchived){archived=isArchived;$('#mode-badge').textContent=isArchived?'LoRA 评测回放 · 非实时推理':'离线工作流 · 模拟工具';$('#mode-badge').classList.toggle('archived',isArchived);}
function add(role,text){$('#welcome')?.remove();const row=document.createElement('div');row.className='row '+role;row.innerHTML=`<div class="bubble">${role==='assistant'?'<div class="label">'+(archived?'ARCHIVED MODEL OUTPUT':'TRIPPILOT')+'</div>':''}${format(text)}</div>`;chat.append(row);chat.scrollTop=chat.scrollHeight;}
function showTools(data){trace.innerHTML='';$('#tool-count').textContent=String(data.tools?.length||0).padStart(2,'0');const label=document.createElement('div');label.className='workflow-label';label.textContent=data.workflow+(archived?' / 归档工具上下文':' / 确定性离线工具');trace.append(label);
 if(!data.tools?.length){const empty=document.createElement('p');empty.className='no-tool';empty.textContent=data.needs_input?'先补全必要信息，此时不调用工具。':'本次无需工具调用。';trace.append(empty);return;}
 data.tools.forEach((tool,index)=>{const item=document.createElement('details');item.className='tool';item.open=true;item.innerHTML=`<summary aria-label="${esc(names[tool.name]||tool.name)}调用详情"><span class="tool-number">0${index+1}</span><span class="tool-name">${esc(tool.name)}</span><span class="tool-state">${esc(archived?'归档':tool.status)}</span></summary><pre>${esc(JSON.stringify(tool.arguments,null,2))}</pre><div class="tool-result">${esc(tool.result_preview)}</div>`;trace.append(item);});trace.scrollTop=0;}
async function json(url,options){const response=await fetch(url,options);const data=await response.json();if(!response.ok)throw Error(data.error||'请求失败');return data;}
async function reset(){await json('/api/reset',{method:'POST'});chat.innerHTML=initialChat;trace.innerHTML=initialTrace;$('#tool-count').textContent='00';input.value='';setMode(false);}
async function ask(query){query=query.trim();if(!query||busy)return;setBusy(true);try{if(archived)await reset();setMode(false);add('user',query);input.value='';const data=await json('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:query})});showTools(data);add('assistant',data.text);}catch(error){add('assistant','暂时无法完成请求，请重试。'+error.message);}finally{setBusy(false);input.focus();}}
$('#form').addEventListener('submit',event=>{event.preventDefault();ask(input.value);});input.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.isComposing){event.preventDefault();ask(input.value);}});
chat.addEventListener('click',event=>{const button=event.target.closest('[data-q]');if(button)ask(button.dataset.q);});
$('#reset').addEventListener('click',async()=>{if(busy)return;setBusy(true);try{await reset();showView(false);}catch(error){add('assistant',error.message);}finally{setBusy(false);input.focus();}});
function showView(isEvaluation){$('#workspace-view').hidden=isEvaluation;$('#evaluation-view').hidden=!isEvaluation;$('#evaluation-tab').classList.toggle('active',isEvaluation);$('#workspace-tab').classList.toggle('active',!isEvaluation);$('#evaluation-tab').setAttribute('aria-selected',String(isEvaluation));$('#workspace-tab').setAttribute('aria-selected',String(!isEvaluation));}
$('#workspace-tab').onclick=()=>showView(false);$('#evaluation-tab').onclick=()=>showView(true);
async function loadEvaluation(){if(evaluation)return evaluation;evaluation=await json('/api/evaluation');const m=evaluation.metrics;$('#metric-cards').innerHTML=[['工具名序列准确率',m.tool_name_sequence_correct,m.tool_targets],['参数 / 工具调用严格匹配',m.tool_call_exact,m.tool_targets],['工具 JSON 合法率',m.valid_tool_json,m.predicted_tool_outputs]].map(([label,n,d])=>`<article class="metric-card"><strong>${(n/d*100).toFixed(n===d?0:2)}%</strong><span>${label}</span><small>${n} / ${d} · 严格统计</small></article>`).join('');$('#evaluation-scope').textContent=`200 条对话 · ${m.targets} 个 Assistant 节点 · ${m.tool_targets} 个工具目标。决策准确率 ${(m.decision_correct/m.targets*100).toFixed(2)}%；非工具回复非空率 ${(m.nonempty_reply/m.reply_targets*100).toFixed(2)}%。`;return evaluation;}
$('#replay').onclick=async()=>{if(busy)return;setBusy(true);try{const data=await loadEvaluation();await reset();setMode(true);chat.innerHTML='<div class="replay-notice">归档样本 #10 · 真实模型预测与评测工具上下文。酒店及评价来自评测数据。</div>';add('user',data.sample.query);showTools(data.sample);add('assistant',data.sample.text);chat.scrollTop=0;}catch(error){add('assistant',error.message);}finally{setBusy(false);}};
loadEvaluation().catch(()=>{$('#evaluation-scope').textContent='评测记录暂不可用，请稍后重试。';});
